<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Parking.Application.Dto\Parking.Application.Dto.csproj" />
    <ProjectReference Include="..\Parking.Domain.Model\Parking.Domain.Model.csproj" />
  </ItemGroup>

</Project>
