// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class FingerprintTemplate
{
    public int id { get; set; }

    public int vehicle_id { get; set; }

    public byte finger_index { get; set; }

    public byte[] template_data { get; set; }

    public int quality_score { get; set; }

    public DateTime enrolled_at { get; set; }

    public int? enrolled_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public virtual User enrolled_byNavigation { get; set; }

    public virtual RegisteredVehicle vehicle { get; set; }
}