// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class FingerprintTemplate
{
    public int Id { get; set; }

    public int VehicleId { get; set; }

    public byte FingerIndex { get; set; }

    public byte[] TemplateData { get; set; }

    public int QualityScore { get; set; }

    public DateTime EnrolledAt { get; set; }

    public int? EnrolledBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual User EnrolledByNavigation { get; set; }

    public virtual RegisteredVehicle Vehicle { get; set; }
}