// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class monthly_vehicle_schedule
{
    public int id { get; set; }

    public int registered_vehicle_id { get; set; }

    public int day_of_week { get; set; }

    public TimeOnly start_time { get; set; }

    public TimeOnly end_time { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public virtual registered_vehicle registered_vehicle { get; set; }
}