// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class parking_slot
{
    public int id { get; set; }

    public int slot_number { get; set; }

    public bool is_occupied { get; set; }

    public long? current_session_id { get; set; }

    public DateTime? updated_at { get; set; }

    public virtual parking_session current_session { get; set; }

    public virtual ICollection<parking_session> parking_sessions { get; set; } = new List<parking_session>();
}