// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class parking_session
{
    public long id { get; set; }

    public string session_code { get; set; }

    public string plate { get; set; }

    public int vehicle_type_id { get; set; }

    public int? registered_vehicle_id { get; set; }

    public DateTime entry_time { get; set; }

    public DateTime? exit_time { get; set; }

    public int? duration_minutes { get; set; }

    public int? chargeable_minutes { get; set; }

    public decimal? amount_due { get; set; }

    public string status { get; set; }

    public string qr_data { get; set; }

    public string entry_photo_path { get; set; }

    public string notes { get; set; }

    public int entry_operator_id { get; set; }

    public int? exit_operator_id { get; set; }

    public DateTime created_at { get; set; }

    public int? created_by { get; set; }

    public DateTime? updated_at { get; set; }

    public int? updated_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public int? parking_slot_id { get; set; }

    public bool has_key_deposit { get; set; }

    public virtual user entry_operator { get; set; }

    public virtual user exit_operator { get; set; }

    public virtual parking_slot parking_slot { get; set; }

    public virtual ICollection<parking_slot> parking_slots { get; set; } = new List<parking_slot>();

    public virtual ICollection<payment> payments { get; set; } = new List<payment>();

    public virtual registered_vehicle registered_vehicle { get; set; }

    public virtual vehicle_type vehicle_type { get; set; }
}