// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class ParkingSession
{
    public long id { get; set; }

    public string session_code { get; set; }

    public string plate { get; set; }

    public int vehicle_type_id { get; set; }

    public int? registered_vehicle_id { get; set; }

    public DateTime entry_time { get; set; }

    public DateTime? exit_time { get; set; }

    public int? duration_minutes { get; set; }

    public int? chargeable_minutes { get; set; }

    public decimal? amount_due { get; set; }

    public string status { get; set; }

    public string qr_data { get; set; }

    public string entry_photo_path { get; set; }

    public string notes { get; set; }

    public int entry_operator_id { get; set; }

    public int? exit_operator_id { get; set; }

    public DateTime created_at { get; set; }

    public int? created_by { get; set; }

    public DateTime? updated_at { get; set; }

    public int? updated_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public int? parking_slot_id { get; set; }

    public bool has_key_deposit { get; set; }

    public virtual User entry_operator { get; set; }

    public virtual User exit_operator { get; set; }

    public virtual ParkingSlot parking_slot { get; set; }

    public virtual ICollection<ParkingSlot> parking_slots { get; set; } = new List<ParkingSlot>();

    public virtual ICollection<Payment> payments { get; set; } = new List<Payment>();

    public virtual RegisteredVehicle registered_vehicle { get; set; }

    public virtual VehicleType vehicle_type { get; set; }
}