// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class ParkingSlot
{
    public int Id { get; set; }

    public int SlotNumber { get; set; }

    public bool IsOccupied { get; set; }

    public long? CurrentSessionId { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ParkingSession CurrentSession { get; set; }

    public virtual ICollection<ParkingSession> ParkingSessions { get; set; } = new List<ParkingSession>();
}