// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema; // <-- AGREGADO PARA EL FOREIGN KEY

namespace Parking.Domain.Model.Models;

public partial class ParkingSession
{
    public long Id { get; set; }

    public string SessionCode { get; set; }

    public string Plate { get; set; }

    public int VehicleTypeId { get; set; }

    public int? RegisteredVehicleId { get; set; }

    public DateTime EntryTime { get; set; }

    public DateTime? ExitTime { get; set; }

    public int? DurationMinutes { get; set; }

    public int? ChargeableMinutes { get; set; }

    public decimal? AmountDue { get; set; }

    public string Status { get; set; }

    public string QrData { get; set; }

    public string EntryPhotoPath { get; set; }

    public string Notes { get; set; }

    public int EntryOperatorId { get; set; }

    public int? ExitOperatorId { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    // <-- SOLUCIÓN AQUÍ: Se le dice explícitamente qué ID usar
    [ForeignKey(nameof(EntryOperatorId))]
    public virtual User EntryOperator { get; set; }

    // <-- SOLUCIÓN AQUÍ: Se le dice explícitamente qué ID usar
    [ForeignKey(nameof(ExitOperatorId))]
    public virtual User ExitOperator { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual RegisteredVehicle RegisteredVehicle { get; set; }

    public virtual VehicleType VehicleType { get; set; }
}