// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class Payment
{
    public long Id { get; set; }

    public long SessionId { get; set; }

    public decimal AmountDue { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentReference { get; set; }

    public int CollectedBy { get; set; }

    public DateTime CollectedAt { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual User CollectedByNavigation { get; set; }

    public virtual ParkingSession Session { get; set; }
}