// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class Payment
{
    public long id { get; set; }

    public long session_id { get; set; }

    public decimal amount_due { get; set; }

    public string payment_method { get; set; }

    public string payment_reference { get; set; }

    public int collected_by { get; set; }

    public DateTime collected_at { get; set; }

    public string notes { get; set; }

    public DateTime created_at { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public virtual User collected_byNavigation { get; set; }

    public virtual ParkingSession session { get; set; }
}