// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class RegisteredVehicle
{
    public int id { get; set; }

    public string plate { get; set; }

    public int vehicle_type_id { get; set; }

    public string owner_name { get; set; }

    public string owner_phone { get; set; }

    public string owner_email { get; set; }

    public string owner_cedula { get; set; }

    public string notes { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public int? created_by { get; set; }

    public DateTime? updated_at { get; set; }

    public int? updated_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public virtual User created_byNavigation { get; set; }

    public virtual ICollection<FingerprintTemplate> fingerprint_templates { get; set; } = new List<FingerprintTemplate>();

    public virtual ICollection<ParkingSession> parking_sessions { get; set; } = new List<ParkingSession>();

    public virtual VehicleType vehicle_type { get; set; }
}