// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class user
{
    public int id { get; set; }

    public string username { get; set; }

    public string password_hash { get; set; }

    public string full_name { get; set; }

    public string role { get; set; }

    public bool is_active { get; set; }

    public DateTime? last_login { get; set; }

    public int login_attempts { get; set; }

    public DateTime? locked_until { get; set; }

    public DateTime created_at { get; set; }

    public int? created_by { get; set; }

    public DateTime? updated_at { get; set; }

    public int? updated_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public virtual ICollection<fingerprint_template> fingerprint_templates { get; set; } = new List<fingerprint_template>();

    public virtual ICollection<parking_session> parking_sessionentry_operators { get; set; } = new List<parking_session>();

    public virtual ICollection<parking_session> parking_sessionexit_operators { get; set; } = new List<parking_session>();

    public virtual ICollection<payment> payments { get; set; } = new List<payment>();

    public virtual ICollection<registered_vehicle> registered_vehicles { get; set; } = new List<registered_vehicle>();
}