// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class vehicle_type
{
    public int id { get; set; }

    public string name { get; set; }

    public string icon { get; set; }

    public decimal hourly_rate { get; set; }

    public bool is_active { get; set; }

    public DateTime created_at { get; set; }

    public int? created_by { get; set; }

    public DateTime? updated_at { get; set; }

    public int? updated_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public int grace_minutes { get; set; }

    public int fraction_minutes { get; set; }

    public decimal fraction_rate { get; set; }

    public virtual ICollection<parking_session> parking_sessions { get; set; } = new List<parking_session>();

    public virtual ICollection<registered_vehicle> registered_vehicles { get; set; } = new List<registered_vehicle>();
}