// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Parking.Domain.Model.Models;

public partial class vehicle_monthly_plan
{
    public int id { get; set; }

    public int registered_vehicle_id { get; set; }

    public decimal monthly_fee { get; set; }

    public DateTime start_date { get; set; }

    public DateTime end_date { get; set; }

    public DateTime payment_date { get; set; }

    public bool is_active { get; set; }

    public string notes { get; set; }

    public DateTime created_at { get; set; }

    public int? created_by { get; set; }

    public DateTime? updated_at { get; set; }

    public int? updated_by { get; set; }

    public bool is_deleted { get; set; }

    public DateTime? deleted_at { get; set; }

    public int? deleted_by { get; set; }

    public string status { get; set; }

    public int? collected_by { get; set; }

    public virtual user collected_byNavigation { get; set; }

    public virtual user created_byNavigation { get; set; }

    public virtual registered_vehicle registered_vehicle { get; set; }
}