// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Parking.Domain.Model.Models;

namespace Parking.Infrastructure.DataAccess;

public partial class parking_dbContext : DbContext
{
    public parking_dbContext(DbContextOptions<parking_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<fingerprint_template> fingerprint_templates { get; set; }

    public virtual DbSet<monthly_vehicle_schedule> monthly_vehicle_schedules { get; set; }

    public virtual DbSet<parking_session> parking_sessions { get; set; }

    public virtual DbSet<parking_slot> parking_slots { get; set; }

    public virtual DbSet<payment> payments { get; set; }

    public virtual DbSet<registered_vehicle> registered_vehicles { get; set; }

    public virtual DbSet<user> users { get; set; }

    public virtual DbSet<vehicle_monthly_plan> vehicle_monthly_plans { get; set; }

    public virtual DbSet<vehicle_type> vehicle_types { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<fingerprint_template>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__fingerpr__3213E83FDBBEBB05");

            entity.Property(e => e.enrolled_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.template_data).IsRequired();

            entity.HasOne(d => d.enrolled_byNavigation).WithMany(p => p.fingerprint_templates)
                .HasForeignKey(d => d.enrolled_by)
                .HasConstraintName("FK__fingerpri__enrol__4222D4EF");

            entity.HasOne(d => d.vehicle).WithMany(p => p.fingerprint_templates)
                .HasForeignKey(d => d.vehicle_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__fingerpri__vehic__412EB0B6");
        });

        modelBuilder.Entity<monthly_vehicle_schedule>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__monthly___3213E83F779E6BD1");

            entity.HasIndex(e => new { e.registered_vehicle_id, e.day_of_week }, "UX_monthly_vehicle_schedule_day")
                .IsUnique()
                .HasFilter("([is_deleted]=(0))");

            entity.Property(e => e.created_at)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.is_active).HasDefaultValue(true);

            entity.HasOne(d => d.created_byNavigation).WithMany(p => p.monthly_vehicle_schedulecreated_byNavigations)
                .HasForeignKey(d => d.created_by)
                .HasConstraintName("FK_monthly_vehicle_schedules_created_by");

            entity.HasOne(d => d.registered_vehicle).WithMany(p => p.monthly_vehicle_schedules)
                .HasForeignKey(d => d.registered_vehicle_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__monthly_v__regis__05D8E0BE");

            entity.HasOne(d => d.updated_byNavigation).WithMany(p => p.monthly_vehicle_scheduleupdated_byNavigations)
                .HasForeignKey(d => d.updated_by)
                .HasConstraintName("FK_monthly_vehicle_schedules_updated_by");
        });

        modelBuilder.Entity<parking_session>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__parking___3213E83F56D9C37C");

            entity.HasIndex(e => e.session_code, "UQ__parking___615A1EA73E5AD186").IsUnique();

            entity.Property(e => e.amount_due).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.entry_photo_path).HasMaxLength(500);
            entity.Property(e => e.plate)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.session_code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.entry_operator).WithMany(p => p.parking_sessionentry_operators)
                .HasForeignKey(d => d.entry_operator_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__parking_s__entry__44FF419A");

            entity.HasOne(d => d.exit_operator).WithMany(p => p.parking_sessionexit_operators)
                .HasForeignKey(d => d.exit_operator_id)
                .HasConstraintName("FK__parking_s__exit___45F365D3");

            entity.HasOne(d => d.parking_slot).WithMany(p => p.parking_sessions)
                .HasForeignKey(d => d.parking_slot_id)
                .HasConstraintName("FK_parking_sessions_slot");

            entity.HasOne(d => d.registered_vehicle).WithMany(p => p.parking_sessions)
                .HasForeignKey(d => d.registered_vehicle_id)
                .HasConstraintName("FK__parking_s__regis__440B1D61");

            entity.HasOne(d => d.vehicle_type).WithMany(p => p.parking_sessions)
                .HasForeignKey(d => d.vehicle_type_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__parking_s__vehic__4316F928");
        });

        modelBuilder.Entity<parking_slot>(entity =>
        {
            entity.Property(e => e.slot_number)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.current_session).WithMany(p => p.parking_slots)
                .HasForeignKey(d => d.current_session_id)
                .HasConstraintName("FK_parking_slots_session");
        });

        modelBuilder.Entity<payment>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__payments__3213E83FC860615E");

            entity.Property(e => e.amount_paid).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.collected_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.payment_method)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.payment_reference).HasMaxLength(100);

            entity.HasOne(d => d.collected_byNavigation).WithMany(p => p.paymentcollected_byNavigations)
                .HasForeignKey(d => d.collected_by)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__payments__collec__47DBAE45");

            entity.HasOne(d => d.session).WithMany(p => p.payments)
                .HasForeignKey(d => d.session_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__payments__sessio__46E78A0C");

            entity.HasOne(d => d.updated_byNavigation).WithMany(p => p.paymentupdated_byNavigations)
                .HasForeignKey(d => d.updated_by)
                .HasConstraintName("FK_payments_updated_by");
        });

        modelBuilder.Entity<registered_vehicle>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__register__3213E83F900EC7EE");

            entity.HasIndex(e => e.plate, "UQ__register__0C04E256A2EE3C46").IsUnique();

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.owner_cedula).HasMaxLength(20);
            entity.Property(e => e.owner_email).HasMaxLength(120);
            entity.Property(e => e.owner_name).HasMaxLength(120);
            entity.Property(e => e.owner_phone).HasMaxLength(20);
            entity.Property(e => e.plate)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.created_byNavigation).WithMany(p => p.registered_vehicles)
                .HasForeignKey(d => d.created_by)
                .HasConstraintName("FK__registere__creat__49C3F6B7");

            entity.HasOne(d => d.vehicle_type).WithMany(p => p.registered_vehicles)
                .HasForeignKey(d => d.vehicle_type_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__registere__vehic__48CFD27E");
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__users__3213E83FF10AB662");

            entity.HasIndex(e => e.username, "UQ__users__F3DBC572AD411580").IsUnique();

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.full_name)
                .IsRequired()
                .HasMaxLength(120);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.password_hash)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.role)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.username)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<vehicle_monthly_plan>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__vehicle___3213E83F61B09F6E");

            entity.HasIndex(e => e.is_active, "IX_vehicle_monthly_plans_active");

            entity.HasIndex(e => new { e.start_date, e.end_date }, "IX_vehicle_monthly_plans_dates");

            entity.HasIndex(e => new { e.status, e.end_date }, "IX_vehicle_monthly_plans_status_enddate");

            entity.HasIndex(e => e.registered_vehicle_id, "IX_vehicle_monthly_plans_vehicle");

            entity.HasIndex(e => e.registered_vehicle_id, "UX_vehicle_monthly_plans_active_vehicle")
                .IsUnique()
                .HasFilter("([is_active]=(1) AND [is_deleted]=(0))");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.monthly_fee).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("active")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_vehicle_monthly_plans_status");

            entity.HasOne(d => d.collected_byNavigation).WithMany(p => p.vehicle_monthly_plancollected_byNavigations)
                .HasForeignKey(d => d.collected_by)
                .HasConstraintName("FK_vehicle_monthly_plans_collected_by");

            entity.HasOne(d => d.created_byNavigation).WithMany(p => p.vehicle_monthly_plancreated_byNavigations)
                .HasForeignKey(d => d.created_by)
                .HasConstraintName("FK_vehicle_monthly_plans_created_by");

            entity.HasOne(d => d.registered_vehicle).WithOne(p => p.vehicle_monthly_plan)
                .HasForeignKey<vehicle_monthly_plan>(d => d.registered_vehicle_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_vehicle_monthly_plans_registered_vehicle");
        });

        modelBuilder.Entity<vehicle_type>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__vehicle___3213E83F3F31EEA0");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.fraction_minutes).HasDefaultValue(15);
            entity.Property(e => e.fraction_rate)
                .HasDefaultValue(0.25m)
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.grace_minutes).HasDefaultValue(5);
            entity.Property(e => e.hourly_rate).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.icon)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.is_active).HasDefaultValue(true);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(60);

            entity.HasOne(d => d.created_byNavigation).WithMany(p => p.vehicle_typecreated_byNavigations)
                .HasForeignKey(d => d.created_by)
                .HasConstraintName("FK_vehicle_types_created_by");

            entity.HasOne(d => d.updated_byNavigation).WithMany(p => p.vehicle_typeupdated_byNavigations)
                .HasForeignKey(d => d.updated_by)
                .HasConstraintName("FK_vehicle_types_updated_by");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}